name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and release SemTK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - shell: bash
        name: Build SemTK
        run: bash ci/build-semtk.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "distribution/target/semtk-opensource-${{ github.ref }}-bin.tar.gz"
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
